# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02fc690febd53396046ba86302757e7a2a6cc3973f9da9faa230f07f53419f4b052689d768c1c0dda4e5a642a3b1d0de99db8ae86168424e68330f6ac871736d

test:
  secret_key_base: de40a9a3d2c2182b00a7dc0f32c0830c7e05333ddaca43f61a285d61e0ee9de75919ad40dfbb3fb3a259099c9a35d44a7186e589181f49cb4f86898f25292109

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
